//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 10:53:33 PM CLT 
//


package com.android.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Publicacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Publicacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idPublicacion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="idTipoPublicacion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="descrTipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Usuario" type="{http://cl.hotoffer/hotoffer}Usuario"/>
 *         &lt;element name="comentario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="precio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tienda" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Geolocalizacion" type="{http://cl.hotoffer/hotoffer}Geolocalizacion"/>
 *         &lt;element name="fechaPublicacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idEstado" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Publicacion", propOrder = {
    "idPublicacion",
    "idTipoPublicacion",
    "descrTipo",
    "usuario",
    "comentario",
    "precio",
    "tienda",
    "geolocalizacion",
    "fechaPublicacion",
    "idEstado"
})
public class Publicacion {

    protected int idPublicacion;
    protected int idTipoPublicacion;
    @XmlElement(required = true)
    protected String descrTipo;
    @XmlElement(name = "Usuario", required = true)
    protected Usuario usuario;
    @XmlElement(required = true)
    protected String comentario;
    @XmlElement(required = true)
    protected String precio;
    protected String tienda;
    @XmlElement(name = "Geolocalizacion", required = true)
    protected Geolocalizacion geolocalizacion;
    @XmlElement(required = true)
    protected String fechaPublicacion;
    protected int idEstado;

    /**
     * Gets the value of the idPublicacion property.
     * 
     */
    public int getIdPublicacion() {
        return idPublicacion;
    }

    /**
     * Sets the value of the idPublicacion property.
     * 
     */
    public void setIdPublicacion(int value) {
        this.idPublicacion = value;
    }

    /**
     * Gets the value of the idTipoPublicacion property.
     * 
     */
    public int getIdTipoPublicacion() {
        return idTipoPublicacion;
    }

    /**
     * Sets the value of the idTipoPublicacion property.
     * 
     */
    public void setIdTipoPublicacion(int value) {
        this.idTipoPublicacion = value;
    }

    /**
     * Gets the value of the descrTipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrTipo() {
        return descrTipo;
    }

    /**
     * Sets the value of the descrTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrTipo(String value) {
        this.descrTipo = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link Usuario }
     *     
     */
    public Usuario getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Usuario }
     *     
     */
    public void setUsuario(Usuario value) {
        this.usuario = value;
    }

    /**
     * Gets the value of the comentario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComentario() {
        return comentario;
    }

    /**
     * Sets the value of the comentario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComentario(String value) {
        this.comentario = value;
    }

    /**
     * Gets the value of the precio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecio() {
        return precio;
    }

    /**
     * Sets the value of the precio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecio(String value) {
        this.precio = value;
    }

    /**
     * Gets the value of the tienda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTienda() {
        return tienda;
    }

    /**
     * Sets the value of the tienda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTienda(String value) {
        this.tienda = value;
    }

    /**
     * Gets the value of the geolocalizacion property.
     * 
     * @return
     *     possible object is
     *     {@link Geolocalizacion }
     *     
     */
    public Geolocalizacion getGeolocalizacion() {
        return geolocalizacion;
    }

    /**
     * Sets the value of the geolocalizacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geolocalizacion }
     *     
     */
    public void setGeolocalizacion(Geolocalizacion value) {
        this.geolocalizacion = value;
    }

    /**
     * Gets the value of the fechaPublicacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaPublicacion() {
        return fechaPublicacion;
    }

    /**
     * Sets the value of the fechaPublicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaPublicacion(String value) {
        this.fechaPublicacion = value;
    }

    /**
     * Gets the value of the idEstado property.
     * 
     */
    public int getIdEstado() {
        return idEstado;
    }

    /**
     * Sets the value of the idEstado property.
     * 
     */
    public void setIdEstado(int value) {
        this.idEstado = value;
    }

}
